name: Run nf-test HLA-HD (licensed)
on:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nonfree:
    name: Run HLA-HD tests
    if: ${{ ( github.event_name == 'push' && github.repository == 'nf-core/hlatyping' ) || github.event.pull_request.head.repo.full_name == 'nf-core/hlatyping' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "25.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install HLA-HD
        run: |
          curl -L -o hlahd.1.7.1.tar.gz.gpg https://raw.githubusercontent.com/nf-core/test-datasets/hlatyping/software/hlahd.1.7.1.tar.gz.gpg
          gpg --batch --yes --pinentry-mode=loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output ${GITHUB_WORKSPACE}/hlahd.1.7.1.tar.gz --decrypt hlahd.1.7.1.tar.gz.gpg

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run nf-test with HLA-HD
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_hlahd,docker --outdir ./results --hlahd_path ${GITHUB_WORKSPACE}/hlahd.1.7.1.tar.gz

      - name: Run nf-test with OptiType+HLA-HD
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_optitype_hlahd,docker --outdir ./results --hlahd_path ${GITHUB_WORKSPACE}/hlahd.1.7.1.tar.gz
